.gitignore, setup.py, spanner_orm/admin/api.py, spanner_orm/admin/metadata.py, spanner_orm/api.py, spanner_orm/condition.py, spanner_orm/model.py, spanner_orm/query.py, spanner_orm/relationship.py, spanner_orm/schemas/column.py, spanner_orm/schemas/index.py, spanner_orm/schemas/index_column.py, spanner_orm/schemas/schema.py, spanner_orm/tests/model_test.py, spanner_orm/tests/models.py, spanner_orm/tests/query_test.py, spanner_orm/type.py, spanner_orm/update.py
In order for the linters to work correctly, # python3 must appear at the
top of each file.
A setup.py file has been added so that this library can be used.
Unit tests have been added to cover some of the functionality in the
library
=> Update the library to put it in a usable state

spanner_orm/admin/api.py, spanner_orm/admin/metadata.py, spanner_orm/api.py, spanner_orm/condition.py, spanner_orm/error.py, spanner_orm/model.py, spanner_orm/query.py, spanner_orm/relationship.py, spanner_orm/schemas/column.py, spanner_orm/tests/api_test.py, spanner_orm/tests/model_test.py, spanner_orm/tests/query_test.py
Adding regression tests for the issue that was fixed in PR #5. As part
of the testing, switched over many places that were detecting errors
caused by improper library usage to better errors than AssertionError
=> Add unit test for spanner connection functionality

spanner_orm/condition.py, spanner_orm/tests/query_test.py
This is needed in order to support pagination of results
=> Add optional offset to limit condition

spanner_orm/api.py
This is how the documentation says to allow multiple reads in a read
only transaction
=> Allow multiple reads in a run_read_only transaction

setup.py, spanner_orm/admin/metadata.py, spanner_orm/condition.py, spanner_orm/tests/query_test.py, spanner_orm/update.py
Some things have been added in a related project such that I want to
query against a list of things, except the things now need two columns
to be specified properly. The way I'm planning to solve this is do an OR
across multiple of these pairs, which requires support for ORs in the
ORM.
While I was in here, I cleaned up some of the other condition
implementations.
=> Add OrCondition

spanner_orm/query.py
We're currently creating a new _SelectSubQuery for each includes
condition for each result row from Spanner, which is unnecessary.
Instead of that, we now create a single _SelectSubQuery for each
includes condition and use it for each result row.
=> Speed up SelectQuery for includes

spanner_orm/admin/metadata.py, spanner_orm/admin/migration_executor.py, spanner_orm/admin/update.py, spanner_orm/condition.py, spanner_orm/field.py, spanner_orm/index.py, spanner_orm/tests/admin_test.py, spanner_orm/tests/migrations_test.py, spanner_orm/tests/model_test.py, spanner_orm/tests/models.py, spanner_orm/tests/query_test.py, spanner_orm/tests/update_test.py
Fixed pytype and pylint errors so that I can start adding type annotations in the next PR
=> Start working on type annotations

spanner_orm/condition.py, spanner_orm/tests/query_test.py
I like passing fields/relations/indexes as attributes from the model
class instead of as raw strings, so I've updated conditions to allow
that.
=> Update conditions to allow passing objects instead of strings

setup.py, spanner_orm/condition.py, spanner_orm/field.py, spanner_orm/index.py, spanner_orm/relationship.py, spanner_orm/tests/query_test.py
Adding type annotation to the building blocks of models so it will be easier to add type annotation to models.
=> Start adding type annotations

spanner_orm/condition.py, spanner_orm/decorator.py, spanner_orm/field.py, spanner_orm/index.py, spanner_orm/relationship.py
Using Type[Any] instead of Type[model.Model] because the latter blows up pytype.
=> Add type annotation to conditions

spanner_orm/admin/api.py, spanner_orm/admin/column.py, spanner_orm/admin/index.py, spanner_orm/admin/index_column.py, spanner_orm/admin/metadata.py, spanner_orm/admin/migration_status.py, spanner_orm/admin/schema.py, spanner_orm/admin/table.py, spanner_orm/admin/update.py, spanner_orm/model.py
Added some annotations to the simpler pieces of admin code. Found a
couple bugs while I was at it and fixed them.
=> Start adding type annotations to admin code

MANIFEST.in, README.md, setup.py, spanner_orm/admin/migration_executor.py, spanner_orm/decorator.py, spanner_orm/tests/decorator_test.py
Updating the README to start describing how to use spanner-orm. Note: Depends on #55, #56, and #57
=> Start adding documentation

README.md, setup.py, spanner_orm/__init__.py, spanner_orm/admin/metadata.py, spanner_orm/admin/migration_executor.py, spanner_orm/admin/scripts.py, spanner_orm/api.py
Ran through creating a database, creating a migration, executing the
migration, and rolling back the migration, updated all the code to make
it actually work. Also updated the documentation to describe the
migration process
=> Make migrations work

spanner_orm/condition.py, spanner_orm/error.py, spanner_orm/field.py, spanner_orm/index.py, spanner_orm/metadata.py, spanner_orm/model.py, spanner_orm/relationship.py, spanner_orm/tests/query_test.py
Asserts are bad for production code paths, replacing them with throwing
ValidationErrors
=> Remove asserts

spanner_orm/api.py
The README refers to documentation on the API methods, so I guess I
should add that
=> Add docstrings to API methods

spanner_orm/api.py, spanner_orm/model.py
Starting to add docstrings to important public methods, model is the
first place to start
=> Add docstrings to model methods

setup.py, spanner_orm/admin/migration_manager.py, spanner_orm/api.py, spanner_orm/condition.py, spanner_orm/metadata.py, spanner_orm/model.py, spanner_orm/query.py, spanner_orm/tests/admin_test.py, spanner_orm/tests/decorator_test.py, spanner_orm/tests/metadata_test.py, spanner_orm/tests/model_test.py, spanner_orm/tests/models.py, spanner_orm/tests/query_test.py, spanner_orm/tests/update_test.py
We were seeing an issue where subclasses were not inheriting index data
from parent classes, and this probably solves that.
=> Add indexes when combining metadata

.gitignore, README.md, spanner_orm/__init__.py, spanner_orm/field.py, spanner_orm/tests/model_api_test.py, spanner_orm/tests/model_test.py, spanner_orm/tests/models.py, spanner_orm/tests/update_test.py
=> Add float type

.gitignore, README.md
* Mention how to run pytype
* Mention how to install Spanner Emulator + run tests
* Add some files related to pytype and the emulator to `.gitignore`
CC @akefeli
=> Update docs with info on running tests

README.md
Suggest the use of virtualenv for running tests and type checking.
=> Suggest the use of virtualenv

spanner_orm/admin/migration_manager.py
See https://github.com/google/pytype/issues/319 for context on the
error.
Addresses #93.
=> Fix pytype error when dynamically importing a python file.

spanner_orm/model.py
I'm going to be moving these around and changing type annotations in a
future commit; this change should make it easier to see those changes.
=> Add trailing comma to some parameter lists.

setup.py, spanner_orm/condition.py, spanner_orm/tests/condition_test.py
I think this will make it significantly easier to write new conditions,
including a STARTS_WITH() condition I want to add. I think it could also
simplify a bunch of the code in the existing conditions.
=> Add Condition for aritrary SQL.

spanner_orm/model.py, spanner_orm/tests/model_test.py
This should save some uninteresting code at call sites where they can
already safely assume the object exists.
=> Add a function to find an object or raise NotFound.

spanner_orm/condition.py, spanner_orm/tests/condition_test.py
This should save some boilerplate.
=> Infer parameter type if possible.

spanner_orm/api.py, spanner_orm/tests/api_test.py
I'm mostly guessing based on context what this code meant to do. As far
as I can tell, the attribute never existed.
=> Fix access to nonexistent attribute

spanner_orm/testlib/spanner_emulator/testlib.py
I'm planning to use the admin API in a test that uses the emulator.
=> Connect the admin API

spanner_orm/condition.py
It can't infer the type of self.relation from the value of
self.foreign_key_relation.
=> Fix pytype errors with IncludesCondition

spanner_orm/tests/field_test.py
I didn't add any tests for StringArray because I'm about to make other changes to it.
=> Add more tests for spanner_orm.field

.github/workflows/test.yaml, README.md, setup.py
After some discussion, I think we settled on trying a little bit harder to support more versions of python.
=> Re-add support for python 3.8
