- spanner_orm/__init__.py
- spanner_orm/admin/api.py
- spanner_orm/admin/metadata.py
- spanner_orm/api.py
- spanner_orm/field.py
- spanner_orm/model.py
- spanner_orm/schemas/column.py
- spanner_orm/schemas/index.py
- spanner_orm/schemas/index_column.py
- spanner_orm/tests/models.py
- spanner_orm/tests/query_test.py
- spanner_orm/update.py
In the future, I'm going to try to add a Field class to clean up some of
these rough spots. For now, just renaming Type to FieldType and type.py
to field.py so that imports will work better. Also moved over the rest
of the imports in non-test to be of the approved style
> Rename Type to FieldType

- spanner_orm/admin/api.py
- spanner_orm/api.py
Fixing the previous attempt to rename _database_connection to
_connection by changing all references to the variable _connection to
_spanner_connection. Also applying the same change to the admin api
> Fix connections in Apis

- spanner_orm/__init__.py
- spanner_orm/admin/metadata.py
- spanner_orm/condition.py
- spanner_orm/field.py
- spanner_orm/model.py
- spanner_orm/schemas/column.py
- spanner_orm/schemas/index.py
- spanner_orm/schemas/index_column.py
- spanner_orm/tests/admin_test.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/models.py
The popular python ORMs populate model metadata from class attributes
instead of class methods. As part of doing this, the field types are now
wrapped in a Field class, that handles the nullability checks.
Still to do: relationships, indices
> Start populating model metadata from attributes

- spanner_orm/__init__.py
- spanner_orm/condition.py
- spanner_orm/model.py
- spanner_orm/query.py
- spanner_orm/relationship.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/models.py
- spanner_orm/tests/query_test.py
Finishes implementing the query result logic for includes conditions,
adds testing to the result processing, and update the metaclass logic to
also generate relationship information from class attributes.
I also stopped liking indexing into model objects, so I removed
__getitem__ and __setitem__
> Implement more of relationships and add them to model metadata

- setup.py
- spanner_orm/admin/metadata.py
- spanner_orm/condition.py
- spanner_orm/field.py
- spanner_orm/model.py
- spanner_orm/schemas/__init__.py
- spanner_orm/schemas/column.py
- spanner_orm/schemas/index.py
- spanner_orm/schemas/index_column.py
- spanner_orm/tests/admin_test.py
- spanner_orm/tests/models.py
- spanner_orm/tests/query_test.py
- spanner_orm/update.py
Added primary_key flag to Field, which is now used in the Model metadata
to fill out the primary_keys method (renamed from primary_index_keys).
Also removed grpc_list_type from Field, as it was pretty useless.
> Populate Model.primary_keys from metadata

- spanner_orm/__init__.py
- spanner_orm/api.py
- spanner_orm/tests/admin_test.py
- spanner_orm/tests/api_test.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/query_test.py
this setup seems to be best practices for a library.  there are probably other places we can add loggin, I only added to api for now.
If a client wants to see these logs, they need to:
`logging.getLogger('spanner_orm').setLevel(logging.DEBUG)`
> adding logging

- spanner_orm/__init__.py
- spanner_orm/admin/api.py
- spanner_orm/tests/api_test.py
The unit test didn't cover this codepath. Added a unit test, fixed the
codepath, and added a shortcut to the SpannerAdminApi
> Fix admin api create_ddl codepath

- spanner_orm/__init__.py
- spanner_orm/model.py
- spanner_orm/update.py
- SpannerError was too deeply nested
- OrderType enum values were too deeply nested
- update.py hadn't yet switched from FieldTypes to Fields
- model.py had (at least) one place still using __getitem__ instead of
__getattr__
- model.py had a (at least) couple of AssertionErrors that could be
caused by client code, which means they should be SpannerErrors instead
> Fixing a couple issues found while starting to use the library

- spanner_orm/model.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/models.py
A project using this library had models that inherited from other
models, and the fields from the base class stopped showing up after
adding the new way of specifying schemas. This should make it work again
> Allow model inheritance

- spanner_orm/condition.py
- spanner_orm/query.py
- spanner_orm/tests/query_test.py
Append a unique index to each parameter name being passed to spanner so
that the parameter names don't conflict. This used to happen, for
instance, when multiple conditions comparing a column against a value
pointed at the same column.
> Allow multiple conditions on the same column

- spanner_orm/admin/api.py
- spanner_orm/admin/metadata.py
- spanner_orm/condition.py
- spanner_orm/model.py
- spanner_orm/query.py
- spanner_orm/relationship.py
- spanner_orm/tests/admin_test.py
- spanner_orm/tests/model_api_test.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/query_test.py
- spanner_orm/update.py
Thie file basically has three different types of methods: methods that
help define a model schema and interact with it (now in the ModelBase
class), methods that use the model schema to interact with Spanner (now
in the ModelMeta class), and objects that represent rows of the table
associated with the model schema (now in the Model class)
As part of this, I got rid of a bunch of @classmethods. Now methods from
the first two categorie have to be called on a model class and methods
from the third category have to be called on a model object instance.
This means that some of the methods in the Model class have to call
methods on the metaclass, which might be a bit odd.
Also some of the methods have turned into properties. This was aided by
getting rid of the @classmethods, as a method can't …
> Refactor model.py to clean it up

- setup.py
- spanner_orm/model.py
- spanner_orm/tests/model_api_test.py
- spanner_orm/tests/model_test.py
@akefeli wanted to be able to force a write to database regardless of
whether the database has a record with the same primary key, so I've
added the force_write flag to the save_batch method to enable this.
I also started adding testing for some of the model methods, and a
couple of bugs I found in the process were fixed.
> Add force_write flag to save_batch

- setup.py
- spanner_orm/api.py
- spanner_orm/model.py
- spanner_orm/tests/model_api_test.py
- spanner_orm/tests/model_test.py
Added delete_batch on ModelMeta to delete batches of rows and delete on Model to delete a single row.
> Implement deleting rows from Spanner

- spanner_orm/api.py
This doesn't add any tests because this is the code that is at the integration point between spanner-orm and the spanner client library. In order to add any reasonable testing, we'd actually need to talk to a spanner instance, but I'm not going to make a publicly accessible spanner instance so that we can have that sort of testing in this repo
> Fix typo in api.py

- spanner_orm/api.py
I think the default BurstyPool with target size 10 isn't going to be
sufficient for our use cases. This will allow specifying a different
session pool when using spanner_orm
> Allow pool to be specified when connecting to Spanner

- spanner_orm/model.py
- spanner_orm/tests/model_test.py
Starting work on improving performance of spanner_orm. Keeping around
separate dictionaries for field values and related items is slower than
storing it in __dict__, and also there's no real reason to do it. To not
break existing clients using .values, I added a `values` property that
constructs the dictionary from all fields.
One changed test is about changing a list after assigning it to a model,
for which I'm not sure the original behavior was actually desired. The
other is that now None values show up in the `values` property, which
shouldn't break any existing behavior
> Remove values dictionary from Model instances

- setup.py
- spanner_orm/field.py
- spanner_orm/model.py
- spanner_orm/tests/admin_test.py
- spanner_orm/tests/api_test.py
- spanner_orm/tests/decorator_test.py
- spanner_orm/tests/model_api_test.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/query_test.py
If the `persisted` flag is True during model instance creation, we
should assume that the values came from Spanner, and thus we don't have
to validate them. Otherwise, we should validate all field values.
Originally we hadn't been running validation on all field values, so we
were allowing some fields to be None when they were not set as nullable.
I've updated the tests so that they pass again after this change.
> Skip validation on values from Spanner

- spanner_orm/model.py
- spanner_orm/tests/model_api_test.py
Adding a method that will make it easier to find multiple rows from
Spanner at the same time, because using the find API is faster than
using execute_sql with a WHERE IN UNNEST(). I debated changing the
find method so that it allows finding multiple rows, but couldn't
decide one way or the other. Thoughts?
> Add find_multi

- setup.py
- spanner_orm/model.py
I'm a little less certain about this change: it makes model
initialization significantly faster, but it does so by directly using
__dict__ (so we skip hitting our overridden __setattr__ method). This
makes it incompatible with using __slots__ later on. On the other hand,
I wasn't super happy with calling super().__setattr__() previously.
I also updated __setattr__ to make it a bit faster when setting
non-model attributes (`in` on a list is somewhat slow, so we avoid
checking primary keys until we have to)
> Skip calling __setattr__ during model __init__

- spanner_orm/model.py
- spanner_orm/tests/model_test.py
After a reload, we try to update all fields, but we're not allowed to
update primary key fields. The test for reload didn't actually exercise
the reload functionality, so I've added a new test that does.
> Fix reload bug

- spanner_orm/model.py
- spanner_orm/query.py
- spanner_orm/relationship.py
- spanner_orm/tests/model_api_test.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/models.py
- spanner_orm/tests/query_test.py
Add __interleaved__ attribute that specifies that a model should be
interleaved in the parent model's table. There is currently no
validation done that verifies the child model is allowed to be
interleaved in the parent model's table, I plan on doing that when I
start working more on migrations
> Allow child models to be interleaved in parent model tables

- setup.py
- spanner_orm/admin/migration.skel
- spanner_orm/admin/migration_manager.py
- spanner_orm/admin/scripts.py
- spanner_orm/tests/migrations/test_1_4a7a7dee0718.py
- spanner_orm/tests/migrations/test_2_5c078bbb4d43.py
- spanner_orm/tests/migrations/test_3_eceb25f170dd.py
- spanner_orm/tests/migrations_test.py
- spanner_orm/tests/update_test.py
Migration files are going to be pretty simple, they contain an id, the
id of the migration the current one depends on, and methods to apply and
rollback the migration that each return a single SchemaUpdate object.
I've added the code to write a migration file, read all migration files,
and order the migrations based on the 'prev_migration' field to
determine what order the migrations have to be applied in.
> Add reading and writing of migration files

- spanner_orm/admin/api.py
- spanner_orm/admin/metadata.py
- spanner_orm/admin/migration_executor.py
- spanner_orm/admin/migration_status.py
- spanner_orm/admin/update.py
- spanner_orm/api.py
- spanner_orm/tests/migrations_test.py
- spanner_orm/tests/update_test.py
After migrations are written, they need to be run against a given
database to be applied. I've added a model to store the migration status
of migrations on the current database and then wrote the executor to
figure out which migrations need to be executed (both for upgrading and
downgrading migrations), execute them, and then update the database to
indicate that the migration has been run.
In talking with @dseomn, I realized that 'project' can be inferred by
the Spanner client libraries, so I've moved that to be an optional
parameter.
> Add code to run migrations against a given Spanner database

- spanner_orm/admin/metadata.py
- spanner_orm/admin/table.py
- spanner_orm/tests/admin_test.py
I had only implemented the write half of this previously. This adds the
read half of handling interleaved tables. That information is stored in
the INFORMATION_SCHEMA.TABLES table, so I've added that model and then
update the metadata object based on the loaded information.
> Update metadata to work with interleaved tables

- spanner_orm/admin/metadata.py
- spanner_orm/index.py
- spanner_orm/model.py
- spanner_orm/tests/admin_test.py
Updating SpannerMetadata to read secondary index data from Spanner and
model Metadata to hold secondary index data.
Also updated the model to be able to access an index as a class attribute
by its name, like already exists for fields and relationships
Note: this revision is based on #38
> Start working on secondary index support

- spanner_orm/admin/metadata.py
- spanner_orm/admin/update.py
- spanner_orm/tests/admin_test.py
- spanner_orm/tests/update_test.py
- Separated out the different types of updates that had been jammed into
one type. ColumnUpdate now AddColumn/DropColumn/AlterColumn, IndexUpdate
now AddIndex/DropIndex.
- Switched from assertions to SpannerErrors, made error messages more
consistent and helpful
- Implemented DropTable updates
- Implemented AddIndex and DropIndex updates
- I tested this in a Python shell and realized that the metadata caching
was incompatible with migrations (as the metadata changes after a
migration is run), so I removed that
> Refactor updates and add index-related updates

- spanner_orm/__init__.py
- spanner_orm/admin/metadata.py
- spanner_orm/admin/update.py
- spanner_orm/condition.py
- spanner_orm/index.py
- spanner_orm/model.py
- spanner_orm/query.py
- spanner_orm/tests/models.py
- spanner_orm/tests/query_test.py
Allow users to specify which index a Spanner query should use by adding
the force_index condition.
Note: This PR depends on #40
> Add force_index condition

- spanner_orm/admin/update.py
- spanner_orm/model.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/models.py
- spanner_orm/tests/query_test.py
- spanner_orm/tests/update_test.py
This really belongs in the update code, so move it from model.Model to
admin.update.CreateTable. Also because creating the table fresh on a new
database also requires involve adding secondary indices, add a helper
method that takes a model and returns the list of ddl necessary to set
up the table for that model.
Note: This PR depends on #40
> Remove creation_ddl from model

- spanner_orm/condition.py
- spanner_orm/relationship.py
I've changed the return type of the constraints property so that
relationships no longer depend on conditions, breaking the circular
dependency.
> Remove circular dependency between conditions and relationships

- spanner_orm/admin/metadata.py
- spanner_orm/model.py
- spanner_orm/registry.py
- spanner_orm/relationship.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/models.py
Right now, in relationships and parent table specifications, specifying
the model name requires a fully-specified class name. Adding a registry
so we don't have to load classes on the fly and instead register classes
as they load, so we can specify a less-qualified class name and avoid
having to read files to resolve a model class
> Make model specification and loading more robust

- spanner_orm/admin/metadata.py
- spanner_orm/metadata.py
- spanner_orm/model.py
model.py has gotten pretty big, so split out Metadata into a separate
file and add type annotations to it. Also the Metadata got confusing
with admin SpannerMetadata, so I'm starting to rename things to make
more sense.
> Add type annotations to model metadata

- spanner_orm/admin/metadata.py
- spanner_orm/metadata.py
- spanner_orm/model.py
- spanner_orm/relationship.py
- spanner_orm/tests/model_api_test.py
- spanner_orm/tests/model_test.py
Added type annotations to model metaclass and model API class. In order
to make things parse correctly, I had to strip the class holding the
model API methods of its metaclass status, but I mostly just turned the
metaclass methods into regular classmethods.
I had to change the Model typehint in relationship to Any, because
pytype choked on it, for unknown reasons. On the other hand, after this
PR, gpylint and pytype run clean
> Add annotations to model metaclass and model API class

- spanner_orm/__init__.py
- spanner_orm/admin/migration.py
- spanner_orm/admin/migration.skel
- spanner_orm/admin/migration_executor.py
- spanner_orm/admin/migration_manager.py
- spanner_orm/tests/migrations/test_1_4a7a7dee0718.py
- spanner_orm/tests/migrations/test_2_5c078bbb4d43.py
- spanner_orm/tests/migrations/test_3_eceb25f170dd.py
- spanner_orm/tests/migrations_test.py
Fixing the TODO from #55. In the process, I noticed that the migration
skeleton didn't work properly, so I fixed the imports and the return
value there.
Note: depends on #55
> Add migration object for stronger typing

- spanner_orm/__init__.py
- spanner_orm/admin/api.py
- spanner_orm/admin/migration_executor.py
- spanner_orm/admin/migration_status.py
- spanner_orm/admin/schema.py
- spanner_orm/admin/update.py
- spanner_orm/api.py
- spanner_orm/model.py
- spanner_orm/tests/api_test.py
- spanner_orm/tests/migrations_test.py
- spanner_orm/tests/model_api_test.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/query_test.py
The code for managing Spanner connections is sort of clunky and I wasn't
able to do things I wanted with it (the primary being you couldn't run
migrations in a process that was also making active queries to the
existing database), so I've split things apart a bit to make that
possible. There's still some more work to allow not using global
connections, but this is enough work for a PR
Note: Depends on #55 and #56
> Refactor connection code

- spanner_orm/admin/update.py
- spanner_orm/condition.py
- spanner_orm/model.py
- spanner_orm/relationship.py
- spanner_orm/tests/admin_test.py
This has been bugging me for a while. Since we switched to having
table metadata in a separate class, using 'schema' to refer to the list
of fields was no longer accurate, so I've renamed those places to
'fields'
> Rename 'schema' to 'fields'

- spanner_orm/model.py
- spanner_orm/tests/model_test.py
Since we're completely resetting the state of the model when we reload()
it, we also need to set start_values appropriately. We ran into an issue
where we were trying to roll back a change on an object, but the save()
didn't cause a write to happen because the start_values had not been
updated, so we thought there were no changes to commit
> Set start_values on model reload

- README.md
- spanner_orm/__init__.py
- spanner_orm/api.py
- spanner_orm/decorator.py
- spanner_orm/model.py
- spanner_orm/table_apis.py
- spanner_orm/tests/decorator_test.py
- spanner_orm/tests/model_api_test.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/query_test.py
While updating a project to use the newest version of spanner-orm, I
found a couple issues:
- The decorators didn't work because api.spanner_api() was being
evaluated too early. Put it inside a generator to delay evaluating until
call time.
- Getting to the helpers that just call methods on the transaction was
pretty unwieldy, as you had to go through api.spanner_api(), which added
unneeded extra layers of mocking in unit tests. Moved all of these out
to top-level functions in spanner_orm.table_apis and added exports to
__init__.py
> Move the transaction lambda helpers out of SpannerApi

- README.md
- spanner_orm/admin/update.py
- spanner_orm/tests/update_test.py
'ON CASCADE DELETE' was a horrible typo, and there were a couple doc
bugs that needed to be fixed.
> Fixing a few bugs

- README.md
- spanner_orm/__init__.py
- spanner_orm/admin/api.py
- spanner_orm/admin/column.py
- spanner_orm/admin/index.py
- spanner_orm/admin/index_column.py
- spanner_orm/admin/metadata.py
- spanner_orm/admin/migration.py
- spanner_orm/admin/migration_executor.py
- spanner_orm/admin/migration_manager.py
- spanner_orm/admin/migration_status.py
- spanner_orm/admin/schema.py
- spanner_orm/admin/scripts.py
- spanner_orm/admin/table.py
- spanner_orm/admin/update.py
- spanner_orm/api.py
- spanner_orm/condition.py
- spanner_orm/decorator.py
- spanner_orm/field.py
- spanner_orm/index.py
- spanner_orm/metadata.py
- spanner_orm/model.py
- spanner_orm/registry.py
- spanner_orm/relationship.py
- spanner_orm/table_apis.py
- spanner_orm/tests/migrations_test.py
Stop deferring type annotation validation to prevent further divergence.
Prevent the migrations_test from modifying migrations in place.
Update documentation on how to create the database.
Don't validate migration_id in migrations/__init__.py.
> Fix some type annotations that diverged.

- setup.py
- spanner_orm/admin/update.py
- spanner_orm/foreign_key_relationship.py
- spanner_orm/metadata.py
- spanner_orm/model.py
- spanner_orm/tests/migrations_emulator_test.py
- spanner_orm/tests/migrations_for_emulator_test/create_foreign_key_test_model.py
- spanner_orm/tests/models.py
- spanner_orm/tests/update_test.py
This PR adds basic support for adding [Cloud Spanner foreign keys](https://cloud.google.com/spanner/docs/foreign-keys/overview) in migrations.
Functionality to remove a foreign key relationship will be added in a follow-up PR.
> Add support for setting foreign keys

- spanner_orm/admin/migration_manager.py
- spanner_orm/model.py
- spanner_orm/query.py
- spanner_orm/relationship.py
- spanner_orm/table_apis.py
- spanner_orm/tests/metadata_test.py
This PR includes the following changes to get pytype to pass at HEAD:
* Remove `ignore`  in `relationship.py` now that pytype issue #234 is fixed. 
* Switch `table_apis.find` and `table_apis.query` to return a list of sequences, and `query.SpannerQuery.processResults` to accept a list of sequences, so that values can be passes between those methods successfully.
* Disable pytype with a TODO if the error was related to metaclasses or `importlib`.
> Get pytype to pass

- spanner_orm/admin/column.py
- spanner_orm/admin/index.py
- spanner_orm/admin/index_column.py
- spanner_orm/admin/migration_status.py
- spanner_orm/admin/table.py
Fields have class attributes of type Field, but instance attributes of
the specific field type (int, str, etc.) This commit is a hack to get
instance attributes to play nicely with pytype. See #97 for a better
long-term solution.
Addresses #93.
> Make pytype infer the correct instance attribute type.

- spanner_orm/model.py
- spanner_orm/tests/metadata_test.py
This fixes bugs where pytype got the type for `meta` wrong because it
only existed on some classes. I'm not 100% sure adding a default (empty)
metadata to classes that didn't previously have it makes sense, but
tests pass and it seems likely to be safe to me.
This change also has the side effect of parsing Model-specific
attributes from the Model class itself (as opposed to just subclasses of
Model), but it doesn't look like Model has any attributes that would be
affected.
Addresses #93.
Tested: Ran tests and pytype.
> Give all ModelMetaclass classes a `meta` attribute.

- spanner_orm/condition.py
- spanner_orm/tests/query_test.py
I've found myself trying to construct some queries like:
```python
states = [
CONST_1,
CONST_2,
CONST_3,
]
spanner_orm.in_list('my-column', states)
```
I'd like to make `states` a tuple because it's a list with a constant set of items but Spanner ORM's type checking is overly restrictive. This PR allows the value passed into `in_list` to be any kind of iterable instead of just lists.
> Allow tuples with in_list

- spanner_orm/decorator.py
- spanner_orm/tests/decorator_test.py
The first parameter to both run_read_only() and run_write() is called
`method`, so if `**kwargs` has a parameter of the same name, there's an
error.
> Fix error when decorated function has a `method` parameter.

- spanner_orm/model.py
- spanner_orm/tests/model_test.py
This parameter is useful for tests that don't need validation but aren't necessarily 'persisted.'
> Skip validation

- spanner_orm/model.py
- spanner_orm/tests/model_test.py
I'd rather not create a transaction to find() and delete(), when I don't
need the result of find() for anything.
> Add method to delete a row by its primary key.

- spanner_orm/admin/migration.skel
One of our internal lints requires that.
Tested: manually
> End the module docstring one liner with punctuation.

- README.md
- spanner_orm/admin/metadata.py
- spanner_orm/admin/migration_executor.py
- spanner_orm/admin/update.py
- spanner_orm/model.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/query_test.py
Note that this change breaks the API, but I think it's worth it. In some
cases, e.g., where(), this avoids needing to pass an unnamed `None`
argument which I think is confusing. In the case of save_batch()'s
`force_write` parameter, I think this can avoid potentially bad bugs.
And in all cases, I think this makes the call sites more clear.
Additionally:
1. Make the `transaction` parameter optional for all methods.
2. Fix some type annotations on those parameters.
> Make option-like parameters (mostly `transaction`) keyword-only.

- spanner_orm/admin/update.py
- spanner_orm/tests/models.py
- spanner_orm/tests/update_test.py
The current CreateTable DDL doesn't support them, and I don't see any
way to create a table and its secondary indexes in a single DDL
statement:
https://cloud.google.com/spanner/docs/data-definition-language#create_table
> Raise an error if a CreateTable update has secondary indexes.

- spanner_orm/condition.py
- spanner_orm/tests/condition_test.py
This makes it possible to use a more restrictive type annotation than
Any, with the main benefit of excluding Optional[primitive] types. With
the old Any, I think there was a risk of code passing
Optional[primitive], only testing when the value isn't None, and getting
errors in production when the value is None. With this change, the type
checker should complain about that code.
> Make Param type inference explicit.

- spanner_orm/tests/condition_test.py
- spanner_orm/tests/migrations_emulator_test.py
- spanner_orm/tests/model_test.py
Resolving symlinks seems to break the tests in some environments, and I
can't think of a reason it would be necessary.
> Use abspath() instead of realpath() for migrations directories.

- spanner_orm/condition.py
- spanner_orm/tests/condition_test.py
This does break the API, but I don't think there's any way for that
breakage to result in subtle bugs, and I think the type checker should
catch any issues. Also, it's a pretty new API that I'm guessing doesn't
have a lot of use yet.
1. This removes escaping logic, which seems like the sort of thing that
could be error-prone. I'd expect switching to a dedicated function to
also help performance, but I haven't tested it.
2. This makes it easier to add more features later. Specifically, I want
to support case-insensitive substring matching.
3. Make the API more powerful. E.g., it's now possible to test if a
value contains a column. (I don't actually need this feature now, but
switching to ArbitraryCondition makes it trivial to provide.)
> Refactor contains() now that ArbitraryCondition exists.

- README.md
- spanner_orm/__init__.py
- spanner_orm/admin/migration.py
- spanner_orm/admin/migration.skel
- spanner_orm/admin/migration_executor.py
- spanner_orm/admin/update.py
SchemaUpdate seems to be designed for DDL (schema) changes, but there
currently doesn't seem to be any way to add a `NOT NULL` column using
only DDL changes. This commit makes it easier to add non-DDL migration
updates; a follow-up commit will add support for backfilling data in a
migration update.
> Make it possible to add non-DDL migration updates.

- spanner_orm/__init__.py
- spanner_orm/admin/api.py
- spanner_orm/admin/update.py
- spanner_orm/tests/models.py
- spanner_orm/tests/update_test.py
This makes it possible to backfill data from migrations, e.g., changing
NULL values to a non-NULL default before making a column `NOT NULL`.
> Add ExecutePartitionedDml migrations update.

- spanner_orm/admin/migration_manager.py
I think this could reduce confusion when there are multiple people
writing migrations in different timezones.
Tested:
Manually created a migration, and it showed up as:
2021-02-03 18:23:19-05:00
> Include seconds and timezone in migration timestamps.

- README.md
@bpg130, I think you were having running tests because of an outdated Spanner emulator version here.
See https://pantheon.corp.google.com/storage/browser/cloud-spanner-emulator/releases for more details.
> Bump Spanner emulator version

- setup.py
- spanner_orm/condition.py
See https://github.com/slezica/python-frozendict/issues/25.
> Migrate from frozendict to immutabledict.

- README.md
- spanner_orm/admin/api.py
- spanner_orm/api.py
- spanner_orm/tests/api_test.py
They provide the some functionality, but from_connection() functions are
more powerful since they let you store the connection information to use
multiple times. It doesn't seem worth the overhead of maintaining both
versions.
> Deprecate connect() functions in favor of from_connection()

- .github/workflows/test.yaml
- README.md
- spanner_orm/tests/conftest.py
It looks like `python setup.py test`, `python -m unittest`, and `pytest`
all import test modules rather than running them as `__main__`, so the
usual parsing with absltest.main() doesn't work. This pytest fixture
seems to work though.
> Parse ABSL flags when running tests

- spanner_orm/admin/update.py
https://cloud.google.com/spanner/docs/data-definition-language#create-index-interleave
> If `T` is the table into which the index is interleaved, then:
> `T` must be a parent of the table being indexed
If I'm understanding that correctly, any table with an interleaved index
will also have an interleaved table too. We already check for
interleaved tables.
> Don't check for interleaved indexes in DropTable

- spanner_orm/__init__.py
- spanner_orm/field.py
- spanner_orm/tests/migrations_emulator_test.py
- spanner_orm/tests/migrations_for_emulator_test/create_unittest_model.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/models.py
- spanner_orm/tests/update_test.py
Basically identical to https://github.com/google/python-spanner-orm/pull/162. Using this as a workaround since checks were not running on that PR
> Add BytesBase64 support

- setup.py
We've been running this in prod with google-cloud-spanner 3.11.1 for many months and things are working fine.
> Relax google-cloud-spanner constraint

- spanner_orm/model.py
- spanner_orm/tests/model_test.py
This makes it a lot easier to see what's wrong when a unit test
assertion about models fails.
> Add __repr__() to Model.

- .github/workflows/test.yaml
- spanner_orm/api.py
- spanner_orm/model.py
- spanner_orm/table_apis.py
- spanner_orm/tests/api_test.py
- spanner_orm/tests/model_test.py
https://github.com/google/pytype/issues/1081 is making
https://github.com/google/python-spanner-orm/pull/171 more difficult, so
we decided to pin pytype rather than add more disable comments.
> Pin pytype to a version before a bug we're seeing a lot of

- spanner_orm/field.py
1. Boolean flag-like positional arguments are unreadable and error-prone when parameters are added or removed, so make them keyword only.
2. Mutable global "constants" can be modified by accident.
> Make some minor things less error-prone

- spanner_orm/field.py
1. Use f-strings.
2. Use repr() conversions (`!r`) to more clearly separate the value causing an error from the error message and to make types more apparent. E.g., f'{value} is not an int' would be really confusing if value is the string '1'.
> Improve string formatting

- .github/workflows/test.yaml
- spanner_orm/admin/migration_manager.py
- spanner_orm/api.py
- spanner_orm/condition.py
- spanner_orm/field.py
- spanner_orm/model.py
- spanner_orm/table_apis.py
- spanner_orm/tests/api_test.py
- spanner_orm/tests/condition_test.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/query_test.py
The import-error bug is annoying, but 1) it would be nice to get updated pytype changes again and 2) this is holding us back from supporting python 3.10.
> Unpin pytype

- README.md
- spanner_orm/admin/column.py
- spanner_orm/admin/update.py
- spanner_orm/condition.py
- spanner_orm/field.py
- spanner_orm/tests/admin_test.py
- spanner_orm/tests/field_test.py
- spanner_orm/tests/model_test.py
- spanner_orm/tests/query_test.py
Aside from
<https://google.github.io/styleguide/pyguide.html#217-function-and-method-decorators>, this makes it possible to have types with parameters. E.g., this makes it possible to add code for something like Array(String(length=20)) for the type ARRAY<STRING(20)>. That way we don't need to define a new FooArray class for each type of array, and we can add support for lengths other than MAX more easily.
This could break any users that use FieldType for anything other than passing to Field, but hopefully the vast majority of uses just pass it to Field.
> Use instances of FieldType instead of classes

- .github/workflows/test.yaml
Most of our PRs are from branches in this repo, so the push trigger covered those. But I don't think the push trigger covers pushes to branches in other repos that have open PRs in this repo.
> Trigger tests for PRs
